Entry.create(name: 'Shane')
Entry.create(name: 'Raphael')
Entry.create(name: 'Blair')
Entry.create(name: 'Danny')
Entry.create(name: 'Gareth')
Entry.create(name: 'Steve')
Entry.create(name: 'Keeffer')